// GENERATED by scripts/measure_landmarks.py from aes-ref/alpha-white-geom.PNG.
// Do not edit by hand; re-run the script instead.

/** Landmarks in normalised reference-image space (x right, y down). */
export const LANDMARKS_NORM = {
  leftIndexTip: [0.47749, 0.43783],
  leftWristEdgeTop: [0.03163, 0.16092],
  leftWristEdgeBottom: [0.02311, 0.27691],
  leftKnuckleHigh: [0.19708, 0.15674],
  leftThumbTip: [0.25608, 0.46813],
  leftPalmLow: [0.36496, 0.5465],
  rightIndexTip: [0.48966, 0.45664],
  rightHandLow: [0.65024, 0.79519],
  rightWristFar: [0.99453, 0.81609],
  rightWrist: [0.68735, 0.67921],
  rightIndexMcp: [0.60219, 0.56949],
} as const satisfies Record<string, readonly [number, number]>;

/** Index-fingertip separation as a fraction of frame width. */
export const FINGERTIP_GAP_FRAC_WIDTH = 0.01637;
