"""Locate the composition landmarks that src/config/composition.ts must reproduce.

Each landmark is the extremal ink pixel inside a hand-chosen search window, so the
numbers are re-derivable from the reference rather than eyeballed once. The dark
threshold separates the drawn hand contour from the lighter construction lines.
Writes outputs/qa/reference-landmarks.json and a marked-up verification image.
"""
import json
from pathlib import Path

import numpy as np
from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parents[1]
REF = ROOT / "aes-ref" / "alpha-white-geom.PNG"
OUT = ROOT / "outputs" / "qa"
OUT.mkdir(parents=True, exist_ok=True)

img = np.asarray(Image.open(REF).convert("L"), dtype=np.float32) / 255.0
H, W = img.shape
ink = (float(np.percentile(img, 99)) - img).clip(0.0, None)

CONTOUR = 0.34   # dark enough to be the drawn outline, not a construction line
PARTICLE = 0.30  # the right hand's dots are dark but small


def extreme(box, key, thresh):
    x0, y0, x1, y1 = box
    sub = ink[y0:y1, x0:x1]
    ys, xs = np.nonzero(sub > thresh)
    if len(xs) == 0:
        return None
    xs, ys = xs + x0, ys + y0
    i = int(np.argmax(key(xs, ys)))
    return [int(xs[i]), int(ys[i])]


# (name, search box, extremal direction, threshold)
SPEC = [
    # left hand — solid sculptural hand entering from the upper left
    ("left_index_tip",        (690, 340, 800, 450), lambda x, y: x + y,      CONTOUR),
    ("left_wrist_edge_top",   (0,   150, 70,  250), lambda x, y: -y,          CONTOUR),
    ("left_wrist_edge_bottom",(0,   190, 60,  340), lambda x, y: y,           CONTOUR),
    ("left_knuckle_high",     (250, 150, 400, 280), lambda x, y: -y,          CONTOUR),
    ("left_thumb_tip",        (380, 390, 500, 500), lambda x, y: -x + 0.5 * y, CONTOUR),
    ("left_palm_low",         (500, 430, 700, 560), lambda x, y: y,           CONTOUR),
    # right hand — particle hand dissolving toward the lower right
    ("right_index_tip",       (795, 400, 900, 500), lambda x, y: -(x + y),    PARTICLE),
    ("right_hand_low",        (850, 640, 1080, 800), lambda x, y: y,          PARTICLE),
    ("right_wrist_far",       (1350, 550, 1644, 957), lambda x, y: x,         PARTICLE),
]

# Read off the reference by eye, not by extremal search: the particle hand's
# wrist is inside the cloud, so there is no extremum to find. Recorded here so
# it appears in the verification overlay and can be re-checked like the rest.
MANUAL = {
    "right_wrist": [1130, 650],
    "right_index_mcp": [990, 545],
}

L = {name: extreme(box, key, th) for name, box, key, th in SPEC}
missing = [k for k, v in L.items() if v is None]
assert not missing, f"no ink found for: {missing}"
L.update(MANUAL)

tipL, tipR = L["left_index_tip"], L["right_index_tip"]
gap = float(np.hypot(tipR[0] - tipL[0], tipR[1] - tipL[1]))

out = {
    "reference": "aes-ref/alpha-white-geom.PNG",
    "size": [W, H],
    "manual_landmarks": sorted(MANUAL),
    "contour_threshold": CONTOUR,
    "particle_threshold": PARTICLE,
    "landmarks_px": L,
    "landmarks_norm": {k: [round(v[0] / W, 5), round(v[1] / H, 5)] for k, v in L.items()},
    "fingertip_gap_px": round(gap, 1),
    "fingertip_gap_frac_width": round(gap / W, 5),
    "fingertip_midpoint_norm": [
        round((tipL[0] + tipR[0]) / 2 / W, 5),
        round((tipL[1] + tipR[1]) / 2 / H, 5),
    ],
}
(OUT / "reference-landmarks.json").write_text(json.dumps(out, indent=2) + "\n")

# verification image: every landmark ringed and labelled on the reference
vis = Image.open(REF).convert("RGB")
d = ImageDraw.Draw(vis)
for name, (x, y) in L.items():
    d.ellipse([x - 11, y - 11, x + 11, y + 11], outline=(210, 40, 40), width=3)
    d.line([x - 18, y, x + 18, y], fill=(210, 40, 40), width=1)
    d.line([x, y - 18, x, y + 18], fill=(210, 40, 40), width=1)
    d.text((x + 15, y + 12), name, fill=(170, 20, 20))
d.line([*tipL, *tipR], fill=(20, 90, 200), width=2)
vis.save(OUT / "reference-landmarks.png")

print(json.dumps(out, indent=2))

# emit the generated TS constants so the app and the measurement never drift apart
CAMEL = {
    "left_index_tip": "leftIndexTip",
    "left_wrist_edge_top": "leftWristEdgeTop",
    "left_wrist_edge_bottom": "leftWristEdgeBottom",
    "left_knuckle_high": "leftKnuckleHigh",
    "left_thumb_tip": "leftThumbTip",
    "left_palm_low": "leftPalmLow",
    "right_wrist": "rightWrist",
    "right_index_mcp": "rightIndexMcp",
    "right_index_tip": "rightIndexTip",
    "right_hand_low": "rightHandLow",
    "right_wrist_far": "rightWristFar",
}
lines = [
    "// GENERATED by scripts/measure_landmarks.py from aes-ref/alpha-white-geom.PNG.",
    "// Do not edit by hand; re-run the script instead.",
    "",
    "/** Landmarks in normalised reference-image space (x right, y down). */",
    "export const LANDMARKS_NORM = {",
]
for k, v in L.items():
    nx, ny = round(v[0] / W, 5), round(v[1] / H, 5)
    lines.append(f"  {CAMEL[k]}: [{nx}, {ny}],")
lines += [
    "} as const satisfies Record<string, readonly [number, number]>;",
    "",
    "/** Index-fingertip separation as a fraction of frame width. */",
    f"export const FINGERTIP_GAP_FRAC_WIDTH = {round(gap / W, 5)};",
    "",
]
(ROOT / "src" / "config" / "referenceLandmarks.generated.ts").write_text("\n".join(lines))
print("\nwrote src/config/referenceLandmarks.generated.ts")
